import Head from 'next/head'
import styles from '../styles/Home.module.css'
import FacebookPage from '../components/FacebookPage'
import { featuredByIndex } from "../public/menuItems";
import Image from 'next/image';
import Link from 'next/link';

const SLIDE_COUNT = 4;
const slides = Array.from(Array(SLIDE_COUNT).keys())
const props = {
  slides: slides,
  images: featuredByIndex
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rock & Wings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className={styles.main}>
        <div style={{ position: 'relative', width: '100vw', height: '66.66vh',
      backgroundColor: 'black'}}>
          <Image src="/logo.png" layout="fill" objectFit='contain'/>
        </div>
        <div className='flex flex-row justify-center items-center bg-black'>
        <Link href="/Contact"><button className="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center m-4  dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">
            Order</button></Link>
          <Link href="/Menu"><button className="text-white bg-red-700 hover:bg-red-800 focus:outline-none focus:ring-4 focus:ring-red-300 font-medium rounded-full text-sm px-5 py-2.5 text-center m-4  dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900">See Our Menu</button></Link>
          
        </div>
        
      </main>
      <div className='flex justify-center items-center bg-black'>
      {/* <FacebookPage/> */}
      </div>
    </div>
  )
}


